---
title: "case study"
output: html_document
---

```{r}
library(p8105.datasets)
library(tidyverse)
```

```{r}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = '90%'
)

theme_set(theme_minimal()+theme(legend.position = 'bottom'))

options(
  ggplot2.continuous.color = 'viridis',
  ggplot2.continuous.fill = 'viridis'
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
data(nyc_airbnb)
nyc_airbnb |> view()
```

## brainstorm questions

-   max and min prices?
-   average price?
-   what factors affect price?
-   price up and down over time?
-   relationship between numbers of reviews and average review?
-   does room type affect availability?
-   location of the unit?
-   popular areas?
-   popularity = number of units? average price?
-   are there repeat hosts? If so, what does that mean?

```{r}
mean(nyc_airbnb$price)
min(nyc_airbnb$price)
max(nyc_airbnb$price)
```

```{r}
nyc_airbnb|>
  filter(price<2500)|>
  ggplot(aes(x = price,y = availability_365,color = neighbourhood_group,shape = room_type))+
  geom_point(alpha = 0.5)
```

```{r}
nyc_airbnb %>%
  ggplot(aes(x = neighbourhood_group, y = log(price))) +
  geom_boxplot()
```

```{r}
nyc_airbnb |>
  ggplot(aes(x = price, fill = room_type)) +
  geom_histogram(position = "dodge") +
  scale_x_continuous(limits = c(0, 250))
```

```{r}
lm_model <- lm(price ~ neighbourhood_group + room_type + minimum_nights + number_of_reviews + availability_365, data = nyc_airbnb)
summary(lm_model)
```

```{r}
nyc_airbnb|>
  ggplot(aes(x = review_scores_location, y = price))+
  geom_point()
```

```{r}
nyc_airbnb|>
  filter(neighbourhood_group == 'Manhattan')|>
  ggplot(aes(x = lat, y = long, color = price))+
  geom_point(alpha = .1)
```

```{r}
nyc_airbnb|>
  filter(neighbourhood_group == 'Manhattan', price<1000, room_type =='Entire home/apt')|>
  group_by(neighbourhood)|>
  summarise(mean_price = mean(price))|>
  arrange(desc(mean_price))
```

```{r}
nyc_airbnb|>
  filter(neighbourhood_group == 'Manhattan', price<1000, room_type =='Entire home/apt')|>
  mutate(neighbourhood = fct_reorder(neighbourhood,price))|>
  ggplot(aes(x = neighbourhood,y = price))+
  geom_violin()+
  theme(axis.text.x = element_text(angle = 30,vjust = 0.85,hjust = 0.75))
```

```{r}
nyc_airbnb|>
  filter(neighbourhood_group =='Manhattan',price < 1000)|>
  leaflet()|>
  addTiles()|>
  addMarkers(~lat,~long)
```
